-- MySQL Script generated by MySQL Workbench
-- Tue Jun 15 21:28:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify-clone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify-clone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify-clone` DEFAULT CHARACTER SET utf8 ;
USE `spotify-clone` ;

-- -----------------------------------------------------
-- Table `spotify-clone`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`),
  UNIQUE INDEX `id-genre_UNIQUE` (`id_genre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`language` (
  `id_language` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_language`),
  UNIQUE INDEX `id-language_UNIQUE` (`id_language` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`content` (
  `id_content` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `length` INT NOT NULL,
  `id_genre` INT NULL DEFAULT NULL,
  `id_language` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_content`),
  UNIQUE INDEX `id-content_UNIQUE` (`id_content` ASC) VISIBLE,
  INDEX `fk_genre_content_idx` (`id_genre` ASC) VISIBLE,
  INDEX `fk_language_content_idx` (`id_language` ASC) VISIBLE,
  CONSTRAINT `fk_genre_content`
    FOREIGN KEY (`id_genre`)
    REFERENCES `spotify-clone`.`genre` (`id_genre`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_language_content`
    FOREIGN KEY (`id_language`)
    REFERENCES `spotify-clone`.`language` (`id_language`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 191
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `id-country_UNIQUE` (`id_country` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(90) NOT NULL,
  `birthdate` DATETIME NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_country` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id-user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_country_user_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_country_user`
    FOREIGN KEY (`id_country`)
    REFERENCES `spotify-clone`.`country` (`id_country`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`playlist` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `id_user` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_playlist`),
  UNIQUE INDEX `id-playlist_UNIQUE` (`id_playlist` ASC) VISIBLE,
  INDEX `fk_user_playlist_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_playlist`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify-clone`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`adds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`adds` (
  `id_playlist` INT NOT NULL,
  `id_content` INT NOT NULL,
  `id_user` INT NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_playlist`, `id_content`),
  INDEX `fk_user_adds_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_content_adds_idx` (`id_content` ASC) VISIBLE,
  CONSTRAINT `fk_content_adds`
    FOREIGN KEY (`id_content`)
    REFERENCES `spotify-clone`.`content` (`id_content`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_adds`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `spotify-clone`.`playlist` (`id_playlist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_adds`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify-clone`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_album`),
  UNIQUE INDEX `id-album_UNIQUE` (`id_album` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`artist` (
  `id_artist` INT NOT NULL AUTO_INCREMENT,
  `stage_name` VARCHAR(90) NOT NULL,
  `birthdate` DATETIME NULL DEFAULT NULL,
  `id_country` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_artist`),
  UNIQUE INDEX `id-artist_UNIQUE` (`id_artist` ASC) VISIBLE,
  INDEX `fk_country_artist_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_country_artist`
    FOREIGN KEY (`id_country`)
    REFERENCES `spotify-clone`.`country` (`id_country`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`device` (
  `id_device` INT NOT NULL AUTO_INCREMENT,
  `mac_address` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `pairing_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_device`),
  UNIQUE INDEX `id-device_UNIQUE` (`id_device` ASC) VISIBLE,
  INDEX `fk_user_device_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_device`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify-clone`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`friends` (
  `id_user1` INT NOT NULL,
  `id_user2` INT NOT NULL,
  PRIMARY KEY (`id_user1`, `id_user2`),
  INDEX `fk_friends_user2_idx` (`id_user2` ASC) VISIBLE,
  CONSTRAINT `fk_user_friends1`
    FOREIGN KEY (`id_user1`)
    REFERENCES `spotify-clone`.`user` (`id_user`),
  CONSTRAINT `fk_user_friends2`
    FOREIGN KEY (`id_user2`)
    REFERENCES `spotify-clone`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`listen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`listen` (
  `id_user` INT NOT NULL,
  `id_content` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_user`, `id_content`, `date`),
  INDEX `fk_content_listen_idx` (`id_content` ASC) VISIBLE,
  CONSTRAINT `fk_content_listen`
    FOREIGN KEY (`id_content`)
    REFERENCES `spotify-clone`.`content` (`id_content`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_listen`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify-clone`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`podcast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`podcast` (
  `id_content` INT NOT NULL,
  `chapter` INT NOT NULL,
  PRIMARY KEY (`id_content`),
  UNIQUE INDEX `chapter_UNIQUE` (`chapter` ASC) VISIBLE,
  CONSTRAINT `fk_content_podcast`
    FOREIGN KEY (`id_content`)
    REFERENCES `spotify-clone`.`content` (`id_content`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`makes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`makes` (
  `id_artist` INT NOT NULL,
  `id_podcast` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_artist`, `id_podcast`),
  INDEX `fk_podcast_makes_idx` (`id_podcast` ASC) VISIBLE,
  CONSTRAINT `fk_artist_makes`
    FOREIGN KEY (`id_artist`)
    REFERENCES `spotify-clone`.`artist` (`id_artist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_podcast_makes`
    FOREIGN KEY (`id_podcast`)
    REFERENCES `spotify-clone`.`podcast` (`id_content`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`prefer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`prefer` (
  `id_user` INT NOT NULL,
  `id_language` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_language`),
  INDEX `fk_language_prefer_idx` (`id_language` ASC) VISIBLE,
  CONSTRAINT `fk_language_prefer`
    FOREIGN KEY (`id_language`)
    REFERENCES `spotify-clone`.`language` (`id_language`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_prefer`
    FOREIGN KEY (`id_user`)
    REFERENCES `spotify-clone`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spotify-clone`.`uploads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify-clone`.`uploads` (
  `id_artist` INT NOT NULL,
  `id_content` INT NOT NULL,
  `id_album` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_artist`, `id_content`, `id_album`),
  INDEX `fk_album_uploads_idx` (`id_album` ASC) VISIBLE,
  INDEX `fk_content_uploads_idx` (`id_content` ASC) VISIBLE,
  CONSTRAINT `fk_album_uploads`
    FOREIGN KEY (`id_album`)
    REFERENCES `spotify-clone`.`album` (`id_album`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artist_uploads`
    FOREIGN KEY (`id_artist`)
    REFERENCES `spotify-clone`.`artist` (`id_artist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_content_uploads`
    FOREIGN KEY (`id_content`)
    REFERENCES `spotify-clone`.`content` (`id_content`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
